### PR TITLE
google analytics 4 pipeline

### PR DESCRIPTION
**Pull request by rudolfix**
we continue #54 here which got merged by accident and had to be reverted

### CODE REVIEW

**Comment by adrianbr** [comment]
end date: always yesterday, do not load "partial, current period"

Run 1. 
If start date exists: Load from start date until end date
Else: Load from start of all time (2000 or similar)  until end date

Run 2.
Load from last_loaded at until end date

**Comment by rudolfix** [comment]
@adrianbr cool we are getting there! What happens if user specifies a new date in run 2? Should we raise error? Should we ignore it (maybe with a warning)? Shpuld we do a full refresh?

**Comment by adrianbr** [comment]
> @adrianbr cool we are getting there! What happens if user specifies a new date in run 2?
I would ignore it. If the user really wants to start loading from earlier, they can just start with a full load.

**Comment by adrianbr** [comment]
After talking with Redi, it seems the most straightforward way to handle it is to only use the start date the first time. If the user resets this to something else, we should warn and carry on

**Review by redicane — APPROVED** [review]

**Review by redicane — APPROVED** [review]

**Review by redicane — DISMISSED** [review]

**Pull request merged**
